@startuml
interface Subject {
    + action()
}

class RealSubject {
    + action()
}

class ProxySubject {
    - RealSubject $realSubject
    + __construct()
    + action()
}

Subject <|.. RealSubject
Subject <|.. ProxySubject
RealSubject <-- ProxySubject
@enduml